name: TerraformAzureDeploy-plan
on:
  push:
    branches: 
    - main
env:
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: ./app1
        run: terraform init

      - name: Terraform Format
        working-directory: ./app1
        run: terraform fmt -recursive    
      
      - name: Terraform Plan
        working-directory: ./app1
        run: terraform plan
      
      - name: Terraform Apply
        working-directory: ./app1
        run: terraform apply --auto-approve
